name: PhelpsRoadClub
favicon: null
layout_spectrum: 0.6121677143964916
typography_spectrum: 0.3154611347708851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5750194266438484
  lightness: 0.286021645180881
  saturation: 0.43461675173603
  rhythmicContrast: 0.8195404352154583
purpose: []
